# Generated by Django 5.2 on 2025-05-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='userdepartment',
            options={'verbose_name': 'Связь пользователей с отделами', 'verbose_name_plural': 'Связи пользователей с отделами'},
        ),
    ]
