# Generated by Django 5.2 on 2025-05-02 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(editable=False, max_length=200)),
                ('outcoming_mail_number', models.CharField(max_length=100)),
                ('outcoming_mail_receiver', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('header', models.CharField(blank=True, max_length=400)),
                ('date', models.DateField(blank=True, null=True)),
                ('outcoming_file', models.FileField(blank=True, null=True, upload_to='%Y_%m-%d/')),
                ('incoming_file', models.FileField(blank=True, null=True, upload_to='%Y_%m-%d/')),
            ],
        ),
    ]
