# Generated by Django 5.2 on 2025-05-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondence',
            options={'verbose_name': 'Корреспонденция', 'verbose_name_plural': 'Корреспонденция'},
        ),
    ]
